// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SlideYourRideServer.Models;

namespace SlideYourRideServer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210623194823_initial2")]
    partial class initial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SlideYourRideServer.Models.Stop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StopDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("SlideYourRideServer.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Elevation")
                        .HasColumnType("int");

                    b.Property<int?>("EndStopId")
                        .HasColumnType("int");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int?>("StartStopId")
                        .HasColumnType("int");

                    b.Property<string>("TrackDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StartStopId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("SlideYourRideServer.Models.Track", b =>
                {
                    b.HasOne("SlideYourRideServer.Models.Stop", "EndStop")
                        .WithMany("EndingTracks")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SlideYourRideServer.Models.Stop", "StartStop")
                        .WithMany("StartingTracks")
                        .HasForeignKey("StartStopId");

                    b.Navigation("EndStop");

                    b.Navigation("StartStop");
                });

            modelBuilder.Entity("SlideYourRideServer.Models.Stop", b =>
                {
                    b.Navigation("EndingTracks");

                    b.Navigation("StartingTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
